#!/bin/bash

CONFIG_PATH=$HOME/.config/projectmanager/
PROJECTS_FILE=${CONFIG_PATH}projects.txt

if [ $1 == open ]; then
    projectname=$(awk '{ printf "%-20s %s\n", $1 ,$2 }' $PROJECTS_FILE | fzf )
    if [ -z "$projectname" ]; then
	    exit
    fi
    projectname=($(echo $projectname | tr [:space:] "\n"))
    projectname=${projectname[0]}
    projectdir=$(grep "\<$projectname\>" $PROJECTS_FILE | awk '{ print $2 }')
    projecttype=$(grep "\<$projectname\>" $PROJECTS_FILE | awk '{ print $3 }')
    case $projecttype in
        jupyter)
            tmux new-window -n $projectname -c $projectdir jupyter notebook
            ;;
        *)
            tmux new-window -n $projectname -c $projectdir nvim .
            ;;
    esac


elif [ $1 == create ]; then
    CREATE_SCRIPT=${CONFIG_PATH}createproject.sh
    tmux new-window $CREATE_SCRIPT

elif [ $1 == edit ]; then
    tmux new-window nvim $PROJECTS_FILE
else
    echo "Help:"
fi
command() { 
}

